name: CI
on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      submodules: false
      envs: |
        - linux: testenv
        - linux: testenv-editable
